//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBShopify
{
    using System;
    using System.Collections.Generic;
    
    public partial class EBayCategoryList
    {
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public string CategoryNumber { get; set; }
        public string StoreCategoryNumber { get; set; }
        public string WebsiteCategoryNumber { get; set; }
        public Nullable<int> WebsiteProductAttributeId { get; set; }
        public Nullable<int> GoogleProductCategory { get; set; }
        public string NewEggCategory { get; set; }
    }
}
