//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBShopify
{
    using System;
    using System.Collections.Generic;
    
    public partial class EbayCategoryStyleList
    {
        public int ID { get; set; }
        public string StyleName { get; set; }
        public string EbayCategoryNumber { get; set; }
    }
}
