//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBShopify
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMarketing
    {
        public int Id { get; set; }
        public string ItemGroupCode2 { get; set; }
        public string ItemTitle { get; set; }
        public string CategoryNumber1 { get; set; }
        public string CategoryNumber2 { get; set; }
        public string EbayStyle1 { get; set; }
        public string EbayStyle2 { get; set; }
        public string EBayDescription { get; set; }
        public string WebSiteDescription { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string WebMetaDescription { get; set; }
    }
}
