//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBShopify
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemInventory
    {
        public System.Guid ID { get; set; }
        public string ListID { get; set; }
        public string UPCCode { get; set; }
        public string ItemGroupCode { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> QuantityOnHand { get; set; }
        public Nullable<int> ReservedQuantity { get; set; }
        public string ItemName { get; set; }
        public string ItemDescription { get; set; }
        public string BrandName { get; set; }
        public string Gender { get; set; }
        public string Color { get; set; }
        public string Color2 { get; set; }
        public string Size { get; set; }
        public string Width { get; set; }
        public Nullable<double> ShippingGrossWeight { get; set; }
        public Nullable<double> ShppingWidth { get; set; }
        public Nullable<double> ShippingHeight { get; set; }
        public Nullable<double> ShippingLenght { get; set; }
        public Nullable<decimal> MinSalesPrice { get; set; }
        public Nullable<decimal> MaxSalesPrice { get; set; }
        public bool IsSellable { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.Guid> SessionID { get; set; }
        public string ItemCodeFull { get; set; }
        public string ItemGroupCode2 { get; set; }
        public Nullable<double> SizeNumeric { get; set; }
        public double AmazonPriceMarkupPercentage { get; set; }
        public int NumericId { get; set; }
        public string MasterGroupCode { get; set; }
        public string MasterColorName { get; set; }
        public Nullable<System.Guid> POBatchId { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<bool> AmazonAvailable { get; set; }
    }
}
