//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBShopify
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemImageLibrary
    {
        public int ItemImageID { get; set; }
        public System.Guid ItemInventoryRefID { get; set; }
        public string ImageType { get; set; }
        public string ImageName { get; set; }
        public string ImageNameTN { get; set; }
        public Nullable<int> QueNumber { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string ItemGroupCode2 { get; set; }
    }
}
