//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBShopify
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShoeSectorDevelopmentEntities : DbContext
    {
        public ShoeSectorDevelopmentEntities()
            : base("name=ShoeSectorDevelopmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EBayCategoryList> EBayCategoryList { get; set; }
        public virtual DbSet<EbayCategoryStyleList> EbayCategoryStyleList { get; set; }
        public virtual DbSet<ItemImageLibrary> ItemImageLibrary { get; set; }
        public virtual DbSet<ItemInventory> ItemInventory { get; set; }
        public virtual DbSet<ItemMarketing> ItemMarketing { get; set; }
        public virtual DbSet<WebSiteItem> WebSiteItem { get; set; }
        public virtual DbSet<WebSiteMasterGroupItem> WebSiteMasterGroupItem { get; set; }
    }
}
