//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBShopify
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSiteItem
    {
        public int Id { get; set; }
        public long WebSiteId { get; set; }
        public string UpcNumber { get; set; }
        public string MasterGroupCode { get; set; }
        public bool IsCompleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
